language: rust
cache: cargo
rust: nightly
install:
  - rustup target add wasm32-unknown-unknown
  - cargo install -f cargo-web
script: cargo web build -Z unstable-options --target=wasm32-unknown-unknown
